### PR TITLE
Fix constraint predicate to be the same as CROSSING/CrySL repo

### PR DESCRIPTION
**Pull request by faustocarva**
Language compatibility correctness

### CODE REVIEW

**Comment by rbonifacio** [comment]
@faustocarva , could you please confirm that the CrySL examples use '[' ']' instead of '(' ')' for these rules. If so, I will be happy to accept this PR.

**Comment by faustocarva** [comment]
https://github.com/CROSSINGTUD/CryptSL/blob/6843933387a6ca17ec096b6f422a403c3cc6c785/de.darmstadt.tu.crossing.CrySL/src/de/darmstadt/tu/crossing/CrySL.xtext#L185

```
PreDefinedPredicates:
	predName="neverTypeOf"+ "[" obj+=[Object] "," type= JvmType"]" |
	predName="noCallTo"+ "[" obj+=[Event] "]" |
	predName="callTo"+ "[" obj+=[Event] "]" |
	predName="notHardCoded"+ "[" obj+=[Object] "]" |
	predName="length"+ "[" obj+=[Object] "]" |
	predName="instanceOf"+ "[" obj+=[Object] "," type = JvmType"]";
```

**Comment by faustocarva** [comment]
https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/11c96359cff24864114c75b334c5c0ae5034eb77/BouncyCastle/src/ECPrivateKeyParameters.crysl#L14
```

CONSTRAINTS
	notHardCoded[d];
```

**Comment by faustocarva** [comment]
https://github.com/CROSSINGTUD/Crypto-API-Rules/blob/11c96359cff24864114c75b334c5c0ae5034eb77/BouncyCastle-JCA/src/KeyManagerFactory.crysl#L24

```
CONSTRAINTS
    neverTypeOf[password, java.lang.String];
```

**Comment by rbonifacio** [comment]
Thanks, that's really enough.

**Pull request merged**
